### ISSUE TITLE
Should we convert this to a site where you can vote?

### ISSUE THREAD

**Issue by spidfire** [JanVanRyswyck/awesome-talks#23]
Maybe we can convert this page to a github page where everyone can contribute and vote (maybe by facebook)?

**Comment by Pondidum** [comment]
Personally I would be against this (especially the Facebook bit) - why over complicate it?

Not sure about others either, but I view this as Jan's list which I would submit a suggestion to, and thus whether to include a link to a talk is down to him, so voting would seem to run against that.

Probably not very community spirited of me though :p

**Comment by JanVanRyswyck** [comment]
This repo is my attempt to create some kind of personal log book of great talks I've watched over the years. The talks on this list have been added because of the awesome presentation skills of the speaker, the game changing content that is being presented or just because it's outright funny. Obviously this is entirely subjective and a matter of personal taste. 

Therefore I look at this list in the same way as I look at a dotfiles repository. A matter of personal taste, a lot of devs have one of their own, where some are more popular than others. I totally love the suggestions. There's a vast amount of conference talks available online, and someone glancing over my list and suggesting one is absolutely the most I want out of it. 

That being said, I would totally want to see anyone else's list (like I glance through dotfiles of other devs looking for those small nuggets that could make a difference) in one form or another that can be a source of inspiration.
